Repository czammar/MNO_finalproject, pull requests merged in 2020-05, with the labels that each got.

#5 Issue 2 aws
  infrastructure/manual_aws.md
Labels: documentation, enhancement

#7 Diagrama de flujo
  README.md
Labels: documentation

#50 agregar fecha como input y documentar función leer datos
  notebooks/Programacion/1ab_extraer_datos_stock.ipynb
Labels: documentation

#51 actualizar ejecuciones en AWS
  infrastructure/Dockerfile
  infrastructure/Solver_AWS.ipynb
  infrastructure/manual_aws.md
Labels: documentation

#53 Referencia de procedencia de Dockerfile
  infrastructure/Dockerfile
Labels: documentation

#54 actualizar notebook
  infrastructure/Solver_AWS.ipynb
Labels: documentation

#61 reporte de resultados v0
  results/ReporteResultados.ipynb
Labels: help wanted

#73 funciones gradiente y Hessiana simbólicas
  notebooks/Programacion/symbolic_gradient_Hessian.ipynb
Labels: enhancement

#76 agregar uso con nuestros reales del problema
  notebooks/Programacion/symbolic_gradient_Hessian.ipynb
Labels: enhancement

#88 gradiente y hessiana sin extender
  notebooks/Programacion/symbolic_gradient_Hessian.ipynb
Labels: enhancement

#89 mejoras sugeridas en la revisión de las funciones
  notebooks/Programacion/symbolic_gradient_Hessian.ipynb
Labels: documentation, enhancement

#106 alinear versiones funciones simbólicas
  notebooks/Programacion/5_Solver_sistema_iterativo.ipynb
  notebooks/Programacion/symbolic_gradient_Hessian.ipynb
Labels: enhancement

#107 alinear funciones simbólicas en carpeta solver
  notebooks/Programacion/solver/optimizacion_numerica.py
Labels: enhancement

#110 agregar códigos utilizados en AWS
  infrastructure/codigos/Solver_Newton.ipynb
  infrastructure/codigos/solver/extraer_datos_yahoo.py
  infrastructure/codigos/solver/funciones_auxiliares.py
  infrastructure/codigos/solver/line_search.py
  infrastructure/codigos/solver/modelo_markowitz.py
  infrastructure/codigos/solver/optimizacion_numerica.py
  infrastructure/codigos/solver/punto_factible.py
  infrastructure/codigos/solver/utils.py
Labels: documentation, enhancement

#121 agregar infraestructura en el reporte
  results/ReporteResultados_v3.ipynb
Labels: documentation
